package school.sptech.conmusicapi.modules.show.util;

public enum ShowStatusEnum {
    UNDEFINED, ARTIST_PROPOSAL, MANAGER_PROPOSAL, NEGOTIATION, ARTIST_ACCEPTED, MANAGER_ACCEPTED,
    CONFIRMED, CONCLUDED, ARTIST_REJECTED, MANAGER_REJECTED, ARTIST_WAIVER, MANAGER_WAIVER,
    ARTIST_CANCELED, MANAGER_CANCELED
}
